build:
    environment:
        php: '7.1'
    tests:
        override:
            -
                command: './vendor/bin/simple-phpunit --coverage-clover=$HOME/build/some-file'
                coverage:
                    file: 'some-file'
                    format: 'php-clover'

filter:
    paths:
        - lib/*
checks:
    php:
        code_rating: true
        duplication: false
